# SPDX-License-Identifier: LGPL-2.1-or-later
# Keep the firmware/vendor logo (ACPI BGRT) and show a spinner under it.
# Falls back to the plain spinner when the firmware provides no logo.
[Daemon]
Theme=bgrt
