# SPDX-License-Identifier: LGPL-2.1-or-later

[Content]
Packages=
        bluez
        bolt
        desktop-file-utils
        pax-utils
        pgpdump
        alsa-utils
        distrobox
        fprintd
        gst-plugin-pipewire
        gst-plugins-good
        hplip
        intel-media-driver
        irqbalance
        libde265
        libva-utils
        pipewire-libcamera
        pipewire-v4l2
        podman
        system-config-printer
        systemd-resolvconf
        tailscale
        thermald
        vulkan-intel
        gst-libav
        gst-plugin-va
        gst-plugins-bad
        gst-plugins-ugly
        networkmanager
        pipewire-jack
        pipewire
        pipewire-alsa
        qemu-guest-agent
        wireless-regdb
        xdg-desktop-portal

# NetworkManager is used in the desktop profiles
RemoveFiles=/usr/lib/systemd/network/89-ethernet.network

KernelCommandLine=plymouth.use-simpledrm splash

KernelInitrdModules=/drivers/gpu/drm

InitrdProfiles=plymouth
