# SPDX-License-Identifier: LGPL-2.1-or-later

# Default locale, /etc/locale.conf is symlinked here by tmpfiles.d/etc.conf.
# localectl set-locale replaces the symlink with a real file in /etc.
LANG=de_DE.UTF-8
LANGUAGE=de_DE:en_US:en
