# SPDX-License-Identifier: LGPL-2.1-or-later

# Default console keymap, /etc/vconsole.conf is symlinked here by
# tmpfiles.d/etc.conf. localectl set-keymap replaces the symlink.
KEYMAP=de-latin1-nodeadkeys
