# SPDX-License-Identifier: LGPL-2.1-or-later
# The ordering fixes have to work in the initrd too, that's where the
# actual unlocking happens. This pulls the same extra tree into the
# default initrd build.
# TO VERIFY on the first test build: that this file is picked up from a
# profile directory and that the relative path resolves. If not, move
# the ExtraTrees= into a top-level mkosi.initrd.conf with a profile
# match.

[Content]
ExtraTrees=mkosi.profiles/swtpm/mkosi.extra
